### ISSUE TITLE
Homebrew installation instructions need fully qualified formula name

### ISSUE THREAD

**Issue by simonwo** [ludovicianul/hq#3]
Hi, the current installation instructions for homebrew:

```
brew tap ludovicianul/tap
brew install hq
```

... install a different tool entirely from homebrew core – your tap is not used.

Instead, you need:

```
brew tap ludovicianul/tap
brew install ludovicianul/tap/hq
```

... which works fine.

**Comment by ludovicianul** [comment]
Thanks! I'll update the README.
